name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile main.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
      - name: Upload main.pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: CV.pdf
