name: Build & publish
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
        
      - name: Compile cv.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: cv.tex
          
      - name: Upload cv.pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: cv.pdf
          
      - name: Set up LaTeX and PDF conversion dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils # Install pdftoppm for PDF conversion

      - name: Convert PDF to PNG for README preview
        run: |
          pdftoppm -f 1 -singlefile -png -scale-to 150 cv.pdf cv-preview

      - name: Commit and push preview image to the repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mv cv-preview.png assets/ # Move the image to the assets folder or another location in the repo
          git add assets/cv-preview.png
          git commit -m "Add PDF preview image"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
